"""FEATURE: Added new custom_url column

Revision ID: 121c19645d22
Revises: 2ec8efa71614
Create Date: 2026-09-25 18:09:22.654775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121c19645d22'
down_revision = '2ec8efa71614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###
