"""Update custom_url length

Revision ID: 1cb24edbe27b
Revises: 121c19645d22
Create Date: 2026-09-25 18:23:54.822915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb24edbe27b'
down_revision = '121c19645d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.alter_column('custom_url',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastes', schema=None) as batch_op:
        batch_op.alter_column('custom_url',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
